services:
  uscitibot:
    build:
      context: /home/shared/.config/uscitibot
      dockerfile: Dockerfile
    image: buonhobo/uscitibot:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: uscitibot
    network_mode: "host"
    volumes:
      - /home/shared/.config/uscitibot:/uscitibot:Z
    deploy:
      restart_policy:
        delay: 180s
        condition: on-failure
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: minipc
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
      - JELLYFIN_PublishedServerUrl=192.168.1.137 #optional
    volumes:
      - /home/shared/.config/jellyfin:/config:Z
      - /home/shared/Media/Jellyfin/Shows:/data/tvshows:z
      - /home/shared/Media/Jellyfin/Movies:/data/movies:z
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
      - UMASK=000
    volumes:
      - /home/shared/.config/qbittorrent-nox:/config:Z
      - /home/shared/Media:/data:z
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
    volumes:
      - /home/shared/.config/sonarr:/config:Z
      - /home/shared/Media:/data:z
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
    volumes:
      - /home/shared/.config/prowlarr:/config:Z
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
    volumes:
      - /home/shared/.config/radarr:/config:Z
      - /home/shared/Media/:/data:z
    ports:
      - 7878:7878
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
    volumes:
      - /home/shared/.config/bazarr:/config:Z
      - /home/shared/Media:/data:z #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
#    environment:
#      - WATCHTOWER_RUN_ONCE=true
    security_opt:
      - "label=disable"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: minipc #optional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
    volumes:
      - /home/shared/.config/syncthing:/config:Z
      - /home/shared/Media/Syncthing:/data:z
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
