name: Build container image

on:
  push:
    paths:
      - ./**
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-and-push-iso:
    permissions:
      packages: write
      contents: read
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: true
          tags: ghcr.io/buonhobo/serverino-bootc:latest